name: IgGM
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aiohttp=3.9.5=py310h2372a71_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - aom=3.9.1=hac33072_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.7=h4faf3ed_1
  - aws-c-cal=0.6.9=h3b91eb8_1
  - aws-c-common=0.9.8=hd590300_0
  - aws-c-compression=0.2.17=hfd9eb17_6
  - aws-c-event-stream=0.3.2=h1fff966_7
  - aws-c-http=0.7.14=hc86c171_2
  - aws-c-io=0.13.36=hc23c90e_0
  - aws-c-mqtt=0.9.10=hba57965_1
  - aws-c-s3=0.4.1=hfadff92_0
  - aws-c-sdkutils=0.1.12=hfd9eb17_5
  - aws-checksums=0.1.17=hfd9eb17_5
  - aws-crt-cpp=0.24.7=h97e63c7_6
  - aws-sdk-cpp=1.11.182=h8beafcf_7
  - biopandas=0.5.1=pyhd8ed1ab_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.7.4=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.1=py310hd41b1e2_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.7.1=h4bc3d14_13
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - debugpy=1.8.2=py310h76e45a6_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.15.4=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py310h5b4e0ec_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.1=py310h2372a71_0
  - fsspec=2024.6.1=pyhff2d567_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py310hc7909c9_1
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=8.5.0=hfac3d4d_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=3.0=h9c3ff4c_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.8.0=hca28451_1
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.10=h7f98852_0
  - libdrm=2.4.122=h4ab18f5_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=14.1.0=h77fa898_0
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglib=2.80.2=hf974151_0
  - libgomp=14.1.0=h77fa898_0
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=11.7.4.75=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.8.0.2=0
  - libopenvino=2024.2.0=h2da1b83_1
  - libopenvino-auto-batch-plugin=2024.2.0=hb045406_1
  - libopenvino-auto-plugin=2024.2.0=hb045406_1
  - libopenvino-hetero-plugin=2024.2.0=h5c03a75_1
  - libopenvino-intel-cpu-plugin=2024.2.0=h2da1b83_1
  - libopenvino-intel-gpu-plugin=2024.2.0=h2da1b83_1
  - libopenvino-intel-npu-plugin=2024.2.0=he02047a_1
  - libopenvino-ir-frontend=2024.2.0=h5c03a75_1
  - libopenvino-onnx-frontend=2024.2.0=h07e8aee_1
  - libopenvino-paddle-frontend=2024.2.0=h07e8aee_1
  - libopenvino-pytorch-frontend=2024.2.0=he02047a_1
  - libopenvino-tensorflow-frontend=2024.2.0=h39126c6_1
  - libopenvino-tensorflow-lite-frontend=2024.2.0=he02047a_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.3.0=h0fcbabc_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=h4ab18f5_2
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - lightning=2.3.3=pyhd8ed1ab_0
  - lightning-utilities=0.11.5=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - looseversion=1.3.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h2372a71_0
  - matplotlib-base=3.9.1=py310h0b1de36_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.8=py310h25c7140_0
  - multidict=6.0.5=py310h2372a71_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h59595ed_0
  - nettle=3.6=he412f7d_0
  - networkx=3.3=pyhd8ed1ab_1
  - ocl-icd=2.3.2=hd590300_1
  - ocl-icd-system=1.0.0=1
  - olefile=0.47=pyhd8ed1ab_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_0
  - openmm=8.1.1=py310h358ce72_1
  - openssl=3.3.1=h4bc722e_2
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py310hf9f9076_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pdbfixer=1.9=pyh1a96a4e_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - psutil=6.0.0=py310hc51659f_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyg=2.5.2=py310_torch_2.0.0_cu117
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyrootutils=1.0.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.14=hd12c33a_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-dotenv=1.0.1=pyhd8ed1ab_0
  - python-lmdb=1.5.1=py310h6a71df1_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-lightning=2.3.3=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - s2n=1.3.56=h06160fa_0
  - scikit-learn=1.5.1=py310h146d792_0
  - scipy=1.14.0=py310h93e2701_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=71.0.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - statsmodels=0.14.2=py310h261611a_0
  - svt-av1=2.1.2=hac33072_0
  - sympy=1.13.0=pypyh2585a3b_103
  - tbb=2021.12.0=h434a139_3
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.0.2=py310_cu117
  - torchdata=0.6.1=py310hdeae4e7_2
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu117
  - tqdm=4.66.4=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wayland=1.23.0=h5291e77_0
  - wayland-protocols=1.36=hd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py310h2372a71_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py310h64cae3c_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - altair==5.3.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - biopython==1.79
      - bleach==6.1.0
      - blinker==1.8.2
      - blis==0.7.11
      - braceexpand==0.1.7
      - cachetools==5.4.0
      - catalogue==2.0.10
      - cfgv==3.4.0
      - click==8.1.7
      - cloudpathlib==0.18.1
      - comm==0.2.2
      - confection==0.1.5
      - contextlib2==21.6.0
      - contexttimer==0.3.3
      - cymem==2.0.8
      - decorator==5.1.1
      - decord==0.6.0
      - deepspeed==0.14.4
      - defusedxml==0.7.1
      - distlib==0.3.8
      - dm-tree==0.1.8
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fairscale==0.4.4
      - fastjsonschema==2.20.0
      - fqdn==1.5.1
      - ftfy==6.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gputil==1.4.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.0
      - hydra-core==1.3.2
      - identify==2.6.0
      - ihm==1.3
      - imageio==2.34.2
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.26.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.11
      - kaggle==1.6.17
      - langcodes==3.4.0
      - language-data==1.2.0
      - lazy-loader==0.4
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-collections==0.1.1
      - modelcif==1.0
      - murmurhash==1.0.10
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.11.1.1
      - nodeenv==1.9.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numpy==1.23.5
      - nvidia-ml-py==12.555.43
      - omegaconf==2.3.0
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - plotly==5.23.0
      - portalocker==2.10.1
      - pre-commit==3.7.1
      - preshed==3.0.9
      - prody==2.4.1
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==5.27.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydeck==0.9.1
      - pygments==2.18.0
      - python-json-logger==2.0.7
      - python-magic==0.4.27
      - python-slugify==8.0.4
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rdkit==2024.3.3
      - referencing==0.35.1
      - regex==2024.5.15
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.19.1
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - smart-open==7.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - stack-data==0.6.3
      - streamlit==1.37.0
      - svgwrite==1.4.3
      - tenacity==8.5.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - text-unidecode==1.3
      - thinc==8.2.5
      - tifffile==2024.7.24
      - timm==0.4.12
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - tornado==6.4.1
      - traitlets==5.14.3
      - transformers==4.43.3
      - tree==0.2.4
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - virtualenv==20.26.3
      - wasabi==1.1.3
      - watchdog==4.0.1
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webcolors==24.6.0
      - webdataset==0.2.86
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
